accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"login/$", views.LoginView.as_view(), name="sign_in"),
    url(r"signup/$", views.SignUpView.as_view(), name="sign_up"),
    url(r"profile/(?P<pk>\d+)/$", views.ProfileDetailView.as_view(),
        name="profile"),
    url(r'edit/(?P<pk>\d+)/$', views.ProfileEditView.as_view(),
        name='profile_edit'),
]

project_team_builder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
                  url(r"^$", views.Home.as_view(), name="home"),
                  url(r'^admin/', admin.site.urls),
                  url(r"^accounts/", include(("accounts.urls", 'accounts'),
                                             namespace='accounts')),
                  url(r"^projects/", include(("projects.urls", 'projects'),
                                             namespace='projects')),
                  url(r"^accounts/", include("django.contrib.auth.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"all", views.AllProjects.as_view(), name="all_projects"
    ),
    url(
        r"(?P<pk>\d+)/detail/$",
        views.ProjectDetailView.as_view(),
        name="detail"),
    url(
        r"(?P<pk>\d+)/positions/(?P<position_pk>\d+)/apply$",
        views.CreateApplicationView.as_view(),
        name="apply"),
    url(
        r"new/$",
        views.CreateProjectPositionView.as_view(),
        name="create_project"),
    url(
        r"(?P<pk>\d+)/edit$",
        views.TestEditView.as_view(),
        name="edit_project"),
    url(
        r"applications/$", views.AllApplications.as_view(), name="applications"
    ),
    url(
        r"applications/(?P<pk>\d+)$", views.ApplicationsDetailView.as_view(),
        name="application_detail"
    ),
    url(
        r"applications/(?P<pk>\d+)/(?P<decision>\w+)$",
        views.AcceptRejectApplicationView.as_view(),
        name="application_decision"),
    url(r'delete/(?P<pk>\d+)$', views.DeleteProjectView.as_view(),
        name='delete'),
]

accounts/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
    PermissionsMixin
)

from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy


class UserManager(BaseUserManager):
    def create_user(self, email, username, display_name=None, password=None):
        if not email:
            raise ValueError("Users must have an email address")
        if not display_name:
            display_name = username

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            display_name=display_name
        )
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, username, display_name, password):
        user = self.create_user(
            email,
            username,
            display_name,
            password
        )
        user.is_staff = True
        user.is_superuser = True
        user.save()
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=40)
    display_name = models.CharField(max_length=140)
    bio = models.TextField(max_length=140, blank=True, default="")
    avatar = models.ImageField(upload_to='avatar_pics/', blank=True, null=True)
    date_joined = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["display_name", "username"]

    def __str__(self):
        return "{}".format(self.display_name)

    def get_short_name(self):
        return self.display_name

    def get_long_name(self):
        return "{} (@{})".format(self.display_name, self.username)

    def get_absolute_url(self):
        return reverse_lazy('accounts:profile', kwargs={'pk': self.pk})


class Skill(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class UserSkill(models.Model):
    skill = models.ForeignKey(Skill, null=True, blank=True,
                              on_delete=models.CASCADE,
                              related_name='user_skill_relation')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='user_skill_relation')

    def __str__(self):
        return '{} - {}'.format(self.user.username,
                                self.skill.name)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django import forms

from . import models


class UserCreationForm(UserCreationForm):
    class Meta:
        fields = ('email', 'password1', 'password2',)
        model = get_user_model()


class EditProfileForm(forms.ModelForm):
    bio = forms.Textarea()
    display_name = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('display_name',
                  'bio',
                  'avatar',)


class UserSkillForm(forms.ModelForm):
    class Meta:
        fields = ('skill',)
        model = models.UserSkill


UserSkillFormSet = forms.modelformset_factory(models.UserSkill,
                                              form=UserSkillForm,
                                              extra=5, min_num=0, max_num=5)

accounts/views.py
from braces.views import PrefetchRelatedMixin
from django.contrib.auth import login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic

from . import models, forms


# Create your views here.


class SignUpView(generic.CreateView):
    form_class = forms.UserCreationForm
    success_url = reverse_lazy('accounts:sign_in')
    template_name = 'accounts/signup.html'


class LoginView(generic.FormView):
    form_class = AuthenticationForm
    success_url = reverse_lazy("home")
    template_name = "accounts/signin.html"

    def get_form(self, form_class=None):
        if form_class is None:
            form_class = self.get_form_class()
        return form_class(self.request, **self.get_form_kwargs())

    def form_valid(self, form):
        login(self.request, form.get_user())
        return super().form_valid(form)


class LogoutView(LoginRequiredMixin, generic.RedirectView):
    url = reverse_lazy("home")

    def get(self, request, *args, **kwargs):
        logout(request)
        return super().get(request, *args, **kwargs)


class ProfileDetailView(LoginRequiredMixin, PrefetchRelatedMixin,
                        generic.DetailView):
    model = models.User
    template_name = "accounts/profile.html"
    prefetch_related = ['user_skill_relation', 'projects']

    def get_object(self, queryset=None):
        return self.get_queryset().get(
            pk=self.request.user.pk
        )


class ProfileEditView(LoginRequiredMixin, generic.UpdateView):
    model = models.User
    template_name = 'accounts/addSkills.html'
    form_class = forms.EditProfileForm

    def get_success_url(self):
        return self.request.user.get_absolute_url()

    def get_context_data(self, **kwargs):
        """ gets the modelset and adds it to the context to be rendered"""
        data = super(ProfileEditView, self).get_context_data(**kwargs)
        user_skills = models.UserSkill.objects.filter(
            user=self.request.user)
        if self.request.POST:
            data_post = self.request.POST
            data['skills'] = forms.UserSkillFormSet(data_post, prefix='skills')
        else:
            data['skills'] = forms.UserSkillFormSet(prefix='skills',
                                                    queryset=user_skills)
        return data

    def form_valid(self, form):
        """ creates or updates form instances based on input"""
        context = self.get_context_data()
        skills_form_set = context['skills']
        skills_form_set.is_valid()
        instances = skills_form_set.save(commit=False)
        for instance in instances:
            instance.user = self.object
            instance.save()
        return super(ProfileEditView, self).form_valid(form)

accounts/templates/accounts/addSkills.html
{% extends "layout.html" %}

{% block body_content %}
    <form method="post" enctype="multipart/form-data"
          class="bounds circle--page">
        {% csrf_token %}
        {{ form.as_p }}
        <ul id="skill_forms" class="circle--clone--list">
            <li> {{ skills }}</li>

        </ul>
        <input type="submit" class="button button-primary icon-on-left"
               value="Save Changes">

    </form>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'layout.html' %}
{% block body_content %}
    {% load static %}
    <div class="circle--actions--bar">
        <nav class="bounds">
            <ul class="circle--pill--list">
                <li>
                    <a href="{% url 'projects:applications' %}">Applications</a>
                </li>
                <li><a class="selected" href="">Profile</a></li>
            </ul>
        </nav>
    </div>

    <div class="bounds circle--page">
        <div class="circle--page--header circle--fluid">
            <div class="circle--fluid--cell circle--fluid--primary">
                <h2>Profile</h2>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <a class="button icon-on-left"
                   href="{% url 'accounts:profile_edit' pk=user.pk %}">Edit or
                    Add skills</a>
            </div>
        </div>

        <div class="grid-70">
            <h1>{{ user.display_name }}</h1>
            <div class="circle--article--body">
                <p>{{ user.bio }}</p>
            </div>

            <h2>Past Projects</h2>
            <table class="u-full-width circle--table">
                <thead>
                <tr>
                    <th>Project Title</th>
                    <th class="circle--cell--right">Project Needs</th>
                </tr>
                </thead>
                <tbody>
                {% for project in user.projects.all %}
                    {% if project.completed %}
                        <tr class="clickable-row"
                            data-href="{% url 'projects:detail' pk=project.pk %}">
                            <td>
                                <h3>{{ project.title }}</h3>
                            </td>
                            <td class="circle--cell--right">
                <span class="secondary-label"><ul>
                    {% for position in project.positions.all %}
                        <li>{{ position.title }}</li>
                    {% endfor %}

                </ul></span>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="grid-25 grid-push-5">

            <div class="circle--secondary--module">
                {% if user.avatar %}
                    <img class="circle--primary--avatar"
                         src="{{ user.avatar.url|default_if_none:'#' }}"
                         width="250" height="250">
                {% endif %}

            </div>

            <div class="circle--secondary--module">
                <h4>My Skills</h4>
                <ul class="unloaded">
                    {% for user_skill in user.user_skill_relation.all %}
                        <li>{{ user_skill.skill }}</li>
                    {% endfor %}
                </ul>
            </div>

            <div class="circle--secondary--module">
                <h4>My Projects</h4>
                <ul class="circle--link--list">
                    {% for project in user.projects.all %}
                        {% if not project.completed %}
                            <li>
                                <a href="{% url 'projects:detail' pk=project.pk %}">{{ project.title }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
        </div>

    </div>
{% endblock %}

accounts/templates/accounts/profile_form.html
{% extends "layout.html" %}

{% block body_content %}
    <form method="post" enctype="multipart/form-data" class="bounds circle--page">
        {% csrf_token %}
        <!--submit btn-->
        <div class="circle--page--header circle--fluid">
            <div class="circle--fluid--cell circle--fluid--primary">
                <h2>Profile</h2>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                <input type="submit" class="button button-primary icon-on-left" value="Save Changes">
            </div>
        </div>

        <div class="grid-70">
            <!--<input type="text" value="Wendy McElroy" placeholder="Full Name" class="circle&#45;&#45;input&#45;&#45;h1">-->
            <div class="circle&#45;&#45;input&#45;&#45;h1">
                {{ form.display_name }}
            </div>
            <div class="circle--article--body">
                {{ form.bio }}
            </div>
        </div>

        <div class="grid-25 grid-push-5">

            <div class="circle--secondary--module">
                <div class="circle--primary--avatar">
                    <a class="button">
                        Upload Photo
                        {{ form.avatar }}
                    </a>
                </div>
            </div>

            <div class="circle--secondary--module">
                <h4>My Skills</h4>

                <ul id="skill_forms" class="circle--clone--list">
                    {{ skills.management_form }}
                    {% for sk_form in skills.forms %}
                        {% for hidden in sk_form.hidden_fields %}
                            {{ hidden }}
                        {% endfor %}
                        <li class="skill_forms">
                            {% if sk_form.instance.pk %}{{ sk_form.DELETE }}{% endif %}
                            {{ sk_form.skill }}
                        </li>
                    {% endfor %}
                </ul>


            </div>
        </div>

    </form>

{% endblock %}

accounts/templates/accounts/signin.html
{% extends "layout.html" %}


{% block body_content %}
    <div class="container">
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Login" class="btn btn-default">
        </form>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "layout.html" %}

{% block body_content %}
    <div class="bounds">
        <h1>Sign Up</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Sign Up" class="btn btn-default">
        </form>
    </div>
{% endblock %}