accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"login/$", views.LoginView.as_view(), name="sign_in"),
    url(r"signup/$", views.SignUpView.as_view(), name="sign_up"),
    url(r"profile/(?P<pk>\d+)/$", views.ProfileDetailView.as_view(),
        name="profile"),
    url(r'edit/(?P<pk>\d+)/$', views.ProfileEditView.as_view(),
        name='profile_edit'),
]

project_team_builder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
                  url(r"^$", views.Home.as_view(), name="home"),
                  url(r'^admin/', admin.site.urls),
                  url(r"^accounts/", include(("accounts.urls", 'accounts'),
                                             namespace='accounts')),
                  url(r"^projects/", include(("projects.urls", 'projects'),
                                             namespace='projects')),
                  url(r"^accounts/", include("django.contrib.auth.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"all", views.AllProjects.as_view(), name="all_projects"
    ),
    url(
        r"(?P<pk>\d+)/detail/$",
        views.ProjectDetailView.as_view(),
        name="detail"),
    url(
        r"(?P<pk>\d+)/positions/(?P<position_pk>\d+)/apply$",
        views.CreateApplicationView.as_view(),
        name="apply"),
    url(
        r"new/$",
        views.CreateProjectPositionView.as_view(),
        name="create_project"),
    url(
        r"(?P<pk>\d+)/edit$",
        views.TestEditView.as_view(),
        name="edit_project"),
    url(
        r"applications/$", views.AllApplications.as_view(), name="applications"
    ),
    url(
        r"applications/(?P<pk>\d+)$", views.ApplicationsDetailView.as_view(),
        name="application_detail"
    ),
    url(
        r"applications/(?P<pk>\d+)/(?P<decision>\w+)$",
        views.AcceptRejectApplicationView.as_view(),
        name="application_decision"),
    url(r'delete/(?P<pk>\d+)$', views.DeleteProjectView.as_view(),
        name='delete'),
]

projects/models.py
from django.conf import settings
from django.db import models
from accounts.models import Skill


# Create your models here.


class Project(models.Model):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE,
                                related_name="projects")
    title = models.CharField(max_length=140)
    description = models.TextField()
    completed = models.BooleanField(default=False)
    time_line_description = models.TextField(default='')
    applicant_req = models.TextField(default='')

    def __str__(self):
        return self.title


class Position(models.Model):
    title = models.CharField(max_length=40)
    skill = models.ForeignKey(Skill, on_delete=models.CASCADE,
                              related_name='positions', )
    description = models.TextField()
    project = models.ForeignKey(Project, on_delete=models.CASCADE,
                                related_name='positions', )
    filled = models.BooleanField(default=False)

    def __str__(self):
        return "{}-{}".format(self.title, self.project)


class Application(models.Model):
    position = models.ForeignKey(Position, on_delete=models.CASCADE,
                                 related_name='applications')
    candidate = models.ForeignKey(settings.AUTH_USER_MODEL,
                                  on_delete=models.CASCADE,
                                  related_name='applications')
    status = models.CharField(max_length=30, default='processing')

    def __str__(self):
        return '{}-{} application'.format(self.position.position_title,
                                          self.candidate)

projects/forms.py
from django import forms
from django.forms import inlineformset_factory
from accounts.models import Skill
from . import models


class ProjectForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'circle--input--h1',
               'placeholder': 'Project Title'}))
    description = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'project description...'}))
    time_line_description = forms.CharField(widget=forms.Textarea(
        attrs={'class': 'circle--textarea--input',
               'placeholder': 'Time estimate'}))

    class Meta:
        model = models.Project
        fields = (
            'title',
            'description',
            'time_line_description',
            'applicant_req'
        )


class PositionForm(forms.ModelForm):
    description = forms.CharField(widget=forms.Textarea(
        attrs={
            'placeholder': 'position description...'}
    )
    )
    skill = forms.ModelChoiceField(
        queryset=Skill.objects.all(),
        empty_label='Select related skill')
    title = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'position name...'}))

    class Meta:
        model = models.Position
        fields = (
            'title',
            'skill',
            'description',
        )


PositionFormSet = inlineformset_factory(models.Project,
                                        models.Position,
                                        form=PositionForm,
                                        extra=5, min_num=0,
                                        can_delete=True)

test = forms.modelformset_factory(models.Position,
                                  form=PositionForm,
                                  extra=2,
                                  can_delete=True)

projects/views.py
from braces.views import PrefetchRelatedMixin, SelectRelatedMixin
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from . import forms
from . import models


class AllProjects(LoginRequiredMixin, PrefetchRelatedMixin, generic.ListView):
    model = models.Project
    prefetch_related = ["positions"]
    template_name = 'index.html'

    def get_queryset(self):
        """returns different querysets based on get received"""
        if self.request.GET.get('q'):
            return models.Project.objects.filter(
                title__icontains=self.request.GET.get('q')
            )
        elif self.request.GET.get('filter'):
            return models.Project.objects.filter(
                positions__title__icontains=self.request.GET.get('filter')
            )
        else:
            return models.Project.objects.all()


class ProjectDetailView(LoginRequiredMixin, PrefetchRelatedMixin,
                        generic.DetailView):
    model = models.Project
    prefetch_related = ["positions"]
    template_name = 'projects/project.html'


class CreateProjectPositionView(LoginRequiredMixin, generic.CreateView):
    form_class = forms.ProjectForm
    model = models.Project
    template_name = 'projects/project_new.html'

    def get_success_url(self):
        return reverse_lazy('projects:detail', kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        """ adds formset to the context data"""
        data = super(CreateProjectPositionView, self).get_context_data(
            **kwargs)
        if self.request.POST:
            data_post = self.request.POST
            data['positions'] = forms.PositionFormSet(data_post,
                                                      prefix='positions')
        else:
            data['positions'] = forms.PositionFormSet(prefix='positions')
        return data

    def form_valid(self, form):
        """ checks if data is valid then sets missing fields of each object
        then saves to database"""
        context = self.get_context_data()
        positions_form_set = context['positions']

        if form.is_valid() and positions_form_set.is_valid():
            self.object = form.save(commit=False)
            self.object.creator = self.request.user
            self.object.save()

            for position_form in positions_form_set:
                if (position_form.cleaned_data.get('skill') and
                        position_form.cleaned_data.get('title')):
                    position_obj = position_form.save(commit=False)
                    position_obj.project = self.object
                    position_obj.save()
        return super(CreateProjectPositionView, self).form_valid(form)


class TestEditView(LoginRequiredMixin, generic.CreateView, generic.UpdateView):
    form_class = forms.ProjectForm
    model = models.Project
    template_name = "projects/project_edit.html"

    def get_success_url(self):
        return reverse_lazy('projects:detail',
                            kwargs={'pk': self.object.pk})

    def get_context_data(self, **kwargs):
        data = super(TestEditView, self).get_context_data(**kwargs)
        user_skills = models.Position.objects.filter(
            project=self.object)
        if self.request.POST:
            data_post = self.request.POST
            data['positions'] = forms.test(data_post, prefix='positions')
        else:
            data['positions'] = forms.test(prefix='positions',
                                           queryset=user_skills)
        return data

    def form_valid(self, form):
        """checks if data is valid then updates or creates new instances"""
        context = self.get_context_data()
        positions_form_set = context['positions']
        positions_form_set.is_valid()
        instances = positions_form_set.save(commit=False)
        for instance in instances:
            instance.project = self.object
            instance.save()
        return super(TestEditView, self).form_valid(form)


class CreateApplicationView(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('projects:detail', kwargs={'pk': self.kwargs.get("pk")})

    def get(self, request, *args, **kwargs):
        """gets the position then checks if a previous application for the
        position already exists, if not it creates a new application"""
        try:
            position = models.Position.objects.get(
                pk=self.kwargs['position_pk'])
        except models.Position.DoesNotExist:
            messages.warning(
                self.request,
                "You can't apply to this position."
            )
        else:
            try:
                previous_application = models.Application.objects.get(
                    position=position,
                    candidate=self.request.user)
            except models.Application.DoesNotExist:
                models.Application.objects.create(
                    position=position,
                    candidate=self.request.user)
                messages.success(self.request, "You have applied to the {}"
                                               " position".format(
                    position.title))

            else:
                messages.warning(
                    self.request,
                    "You can't apply to the same position twice"
                )
        return super().get(request, *args, **kwargs)


class AllApplications(LoginRequiredMixin, PrefetchRelatedMixin,
                      generic.ListView):
    model = models.Application
    prefetch_related = ["candidate", "position"]
    template_name = 'projects/applications.html'

    def get_context_data(self, *args, **kwargs):
        """adds the projects created by the user to the context"""
        context = super(AllApplications, self).get_context_data(*args,
                                                                **kwargs)
        context['projects'] = models.Project.objects.filter(
            creator=self.request.user)
        return context

    def get_queryset(self):
        """gets the queryset based on get kwargs passed in
        to filter the results """
        apps = models.Application.objects.filter(
            position__project__creator=self.request.user
        )

        if self.request.GET.get('pk'):
            apps = apps.filter(
                position__project__pk=self.request.GET.get('pk')
            )
        elif self.request.GET.get('status'):
            apps = apps.filter(
                status=self.request.GET.get('status')
            )

        elif self.request.GET.get('filter'):
            apps = apps.filter(
                position__title__icontains=self.request.GET.get('filter')
            )
        else:
            apps = apps.filter(
                status='processing'
            )


        return apps


class ApplicationsDetailView(LoginRequiredMixin, SelectRelatedMixin,
                             generic.DetailView):
    model = models.Application
    select_related = ["candidate"]


class AcceptRejectApplicationView(LoginRequiredMixin, generic.RedirectView):
    url = reverse_lazy('projects:applications')

    def get_object(self):
        return get_object_or_404(models.Application, pk=self.kwargs.get('pk'))

    def get(self, request, *args, **kwargs):
        """ sets the application status field to the kwarg received .
        sends thr applicant a email of the decision made
         then redirects back to the applications"""
        application = self.get_object()

        decision = self.kwargs.get('decision')
        application.status = decision
        if decision == 'Accepted':
            application.position.filled = True
            application.position.save()

        application.save()
        send_mail(
            '{} application'.format(application.position.title),
            'Your application has been {}'.format(decision),
            'ProjectBuilder.com',
            [application.candidate.email],
            fail_silently=False,
        )

        return super().get(request, *args, **kwargs)


class DeleteProjectView(LoginRequiredMixin, generic.DeleteView):
    model = models.Project
    template_name = 'projects/delete_project.html'
    success_url = reverse_lazy('projects:all_projects')

    def delete(self, *args, **kwargs):
        """deletes the project notifies user of such action """
        messages.success(self.request, "You have Successfully deleted"
                                       " a project")
        return super().delete(*args, **kwargs)

projects/templates/projects/application_detail.html
{% extends 'layout.html' %}
{% block body_content %}
  <div class="circle--actions--bar">
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header circle--fluid">
      <div class="circle--fluid--cell circle--fluid--primary">
        <h2>Candidate Profile</h2>
      </div>

    </div>

    <div class="grid-70">
      <h1>{{ application.candidate.display_name }}</h1>
      <div class="circle--article--body">
        <p>{{ application.candidate.bio }}</p>

        </div>

      <h2>Project application for positon </h2>
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Application role</th>
            <th class="circle--cell--right">Accept or Reject</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <h3>{{ application.position.title }}</h3>
            </td>
            <td class="circle--cell--right">
                <span class="secondary-label"><ul>
                    <li><a href="{% url 'projects:application_decision' pk=application.pk decision='Accepted' %}">Accept</a></li>
                    <li><a href="{% url 'projects:application_decision' pk=application.pk decision='Rejected' %}">
                    Reject
                </a></li>


                </ul></span>
            </td>
          </tr>

        </tbody>
      </table>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <div class="circle--primary--avatar">

        </div>
      </div>

      <div class="circle--secondary--module">
        <h4>Candidate Skills</h4>
        <ul class="unloaded">
            {% for user_skill in application.candidate.user_skill_relation.all %}
          <li>{{ user_skill.skill }}</li>
            {% endfor %}
        </ul>
      </div>

     
    </div>

  </div>
{% endblock %}

projects/templates/projects/applications.html
{% extends 'layout.html' %}
{% block body_content %}
  <div class="circle--actions--bar">
    <nav class="bounds">
      <ul class="circle--pill--list">
        <li><a class="selected" href="">Applications</a></li>
        <li><a href="{% url 'accounts:profile' pk=user.pk %}">Profile</a></li>
      </ul>
    </nav>
  </div>

  <div class="bounds circle--page">
    <div class="circle--page--header grid-100">
      <h2>Applications</h2>
    </div>

    <div class="grid-25">
      <div class="circle--filter circle--secondary--module">
        <h4>Status</h4>
        <ul class="circle--filter--list">
            {% url 'projects:applications' as test %}
          <li><a href="{% url 'projects:applications' %}" {% if request.get_full_path == test %}
                class="selected"
            {% endif %} >New Applications</a></li>
          <li><a href="?status=Accepted" {% if 'Accepted' in request.get_full_path  %}
                class="selected"
            {% endif %} >Accepted</a></li>
          <li><a href="?status=Rejected" {% if 'Rejected' in request.get_full_path  %}
                class="selected"
            {% endif %} >Rejected</a></li>
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>My Projects</h4>
        <ul class="circle--filter--list">
        <li><a class="selected">All Projects</a></li>
            {% for project in projects  %}
               <li><a href="?pk={{ project.pk }}"> {{ project.title }}</a></li>
            {% endfor %}
        </ul>
      </div>

      <div class="circle--filter circle--secondary--module">
        <h4>Project Needs</h4>
        <ul class="circle--filter--list">
           {% url 'projects:applications' as test %}
          <li><a  {% if request.get_full_path == test %}
                class="selected"
            {% endif %} >All Needs</a></li>
          <li><a href="?filter=android"  {% if 'android' in request.get_full_path  %}
                class="selected"
            {% endif %}>Android Developer</a></li>
          <li><a href="?filter=designer"  {% if 'designer' in request.get_full_path  %}
                class="selected"
            {% endif %}>Designer</a></li>
          <li><a href="?filter=java"  {% if 'java' in request.get_full_path  %}
                class="selected"
            {% endif %}>Java Developer</a></li>
          <li><a href="?filter=php"  {% if 'php' in request.get_full_path  %}
                class="selected"
            {% endif %}>PHP Developer</a></li>
          <li><a href="?filter=python"  {% if 'python' in request.get_full_path  %}
                class="selected"
            {% endif %}>Python Developer</a></li>
          <li><a href="?filter=Rails"  {% if 'Rails' in request.get_full_path  %}
                class="selected"
            {% endif %}>Rails Developer</a></li>
          <li><a href="?filter=wordpress"  {% if 'wordpress' in request.get_full_path  %}
                class="selected"
            {% endif %}>WordPress Developer</a></li>
          <li><a href="?filter=ios"  {% if 'ios' in request.get_full_path  %}
                class="selected"
            {% endif %}>iOS Developer</a></li>
        </ul>
      </div>

    </div>

    <div class="grid-70 grid-push-5">
      <table class="u-full-width circle--table">
        <thead>
          <tr>
            <th>Applicant</th>
            <th class="circle--cell--right">Applicant Position</th>
          </tr>
        </thead>
        <tbody>
        {% for application in application_list  %}

          <tr class="clickable-row" data-href="{% url 'projects:application_detail' pk=application.pk %}">
            <td>
              <h3>{{ application.candidate }}</h3>
              <p>{{ application.position.project }}</p>
            </td>
            <td class="circle--cell--right">
              <span class="secondary-label">{{ application.position.title }}</span>
            </td>
          </tr>
        {% endfor %}
        </tbody>
      </table>

    </div>

  </div>
{% endblock %}

projects/templates/projects/delete_project.html
{% extends "layout.html" %}
{% block body_content %}
<div class="bounds">
	<div class="grid-90 centered">
		<h1>Delete Project</h1>
		<p>Are you sure you want to delete this project?</p>
		<form method="POST">
			{% csrf_token %}
			<input type="submit" value="Delete" class="button button-primary">
			<a href="{% url 'projects:all_projects' %}" class="button">Close</a>
		</form>
	</div>
</div>
{% endblock %}

projects/templates/projects/project.html
{% extends 'layout.html' %}
{% block body_content %}
{% if project.creator_id == request.user.pk %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <a class="button" href="{% url 'projects:edit_project' pk=project.pk %}">Edit Project</a>
        <a class="button button-text" href="{% url 'projects:delete' pk=project.pk %}">Delete Project</a>

      </div>
    </div>
  </div>
 {% endif %}
  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--header">
        <h4 class="circle--article--section">Project</h4>
        <h1 class="circle--article--title">{{ project.title }}</h1>
          <p class="circle--article--byline">Project Owner: <a>{{ project.creator }}</a></p>
      </div>

      <div class="circle--article--body">
        <p>{{ project.description }}</p>

        </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>

        <ul class="circle--group--list">
            {% for position in project.positions.all %}
          <li>
            <h3>{{ position }}</h3>
            <p>{{ position.description }}</p>
              {% if not position.filled and project.creator_id != request.user.pk %}
            <a href="{% url 'projects:apply' pk=project.pk position_pk=position.pk %}" class="button button-primary">Apply</a>
                  {% elif project.creator_id == request.user.pk and not position.filled %}
                  <a href="{% url 'projects:applications' %}" class="button button-primary">see applications</a>
                  {% else %}
                  <a href="" class="button button-primary">Filled</a>
          {% endif %}
          </li>
            {% endfor %}
        </ul>
      </div>

    </div>

    <div class="grid-25 grid-push-5">
      <div class="circle--secondary--module">
        <h3>Project Needs</h3>

        <ul class="circle--link--list">
            {% for position in project.positions.all%}
          <li><a>{{ position.skill }}</a></li>
            {% endfor %}
        </ul>
      </div>

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        <p>{{ project.time_line_description }}</p>
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        <p>{{ project.applicant_req }}</p>
      </div>

    </div>
  </div>
{% endblock %}

projects/templates/projects/project_edit.html
{% extends "layout.html" %}

{% block body_content %}

<form  method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <div class="circle--actions--bar">
        <div class="bounds">
            <div class="grid-100">
                <input type="submit" class="button button-primary" value="Save Project"/>
                <a class="button button-text" href="{% url 'home' %}">Discard</a>
            </div>
        </div>
    </div>

    <div class="bounds circle--page circle--article">

        <div class="grid-70">
            <div class="circle--article--body">
                {{ form.title }}
                {{ form.description }}
            </div>

            <div class="circle--project--positions">
                <h2>Positions</h2>

                <ul id="position_forms" class="circle--group--list circle--clone--list">
                    <li class="position_forms">
                        {{ positions }}
                    </li>

                </ul>
                <input type="submit" class="button button-primary" value="Save Project"/>

            </div>
        </div>

        <div class="grid-25 grid-push-5">

            <div class="circle--secondary--module">
                <h3>Project Timeline</h3>
                {{ form.time_line_description }}
            </div>

            <div class="circle--secondary--module">
                <h3>Applicant Requirements</h3>
                {{ form.applicant_req }}
            </div>

        </div>
    </div>
</form>

<script>
    $('.position_forms').formset({
        addText: 'Add Position',
        deleteText: 'Remove',
        addCssClass: 'circle--clone--add',
        deleteCssClass: 'circle--clone--remove',
        prefix: '{{ positions.prefix }}'
    });
</script>

{% endblock %}

projects/templates/projects/project_new.html
{% extends 'layout.html' %}
{% block body_content %}
    <form method="post" enctype="multipart/form-data" class="bounds circle--page">
    {% csrf_token %}
  <div class="circle--actions--bar">
    <div class="bounds">
      <div class="grid-100">
        <input type="submit" class="button button-primary icon-on-left" value="Save">
        <a class="button button-text" href="index.html">Discard</a>
      </div>
    </div>
  </div>

  <div class="bounds circle--page circle--article">
    <div class="grid-70">
      <div class="circle--article--body">
        {{ form.title }}
        {{ form.description }}
      </div>

      <div class="circle--project--positions">
        <h2>Positions</h2>
        {{ positions.management_form }}
        <ul class="circle--group--list circle--clone--list">
            {% for position_form in positions %}
          <li>
            {{ position_form.title }}
            {{ position_form.description }}
              {{ position_form.skill }}
            <a class="circle--clone--add">Add Position</a>
            <a class="circle--clone--remove">Remove</a>
          </li>
            {% endfor %}
        </ul>
        <input type="submit" class="button button-primary icon-on-left" value="Save">

      </div>
    </div>

    <div class="grid-25 grid-push-5">

      <div class="circle--secondary--module">
        <h3>Project Timeline</h3>
        {{ form.time_line_description}}
      </div>

      <div class="circle--secondary--module">
        <h3>Applicant Requirements</h3>
        {{ form.applicant_req }}
      </div>

    </div>
  </div>
    </form>
{% endblock %}