accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"login/$", views.LoginView.as_view(), name="sign_in"),
    url(r"signup/$", views.SignUpView.as_view(), name="sign_up"),
    url(r"profile/(?P<pk>\d+)/$", views.ProfileDetailView.as_view(),
        name="profile"),
    url(r'edit/(?P<pk>\d+)/$', views.ProfileEditView.as_view(),
        name='profile_edit'),
]

project_team_builder/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views

urlpatterns = [
                  url(r"^$", views.Home.as_view(), name="home"),
                  url(r'^admin/', admin.site.urls),
                  url(r"^accounts/", include(("accounts.urls", 'accounts'),
                                             namespace='accounts')),
                  url(r"^projects/", include(("projects.urls", 'projects'),
                                             namespace='projects')),
                  url(r"^accounts/", include("django.contrib.auth.urls"))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        r"all", views.AllProjects.as_view(), name="all_projects"
    ),
    url(
        r"(?P<pk>\d+)/detail/$",
        views.ProjectDetailView.as_view(),
        name="detail"),
    url(
        r"(?P<pk>\d+)/positions/(?P<position_pk>\d+)/apply$",
        views.CreateApplicationView.as_view(),
        name="apply"),
    url(
        r"new/$",
        views.CreateProjectPositionView.as_view(),
        name="create_project"),
    url(
        r"(?P<pk>\d+)/edit$",
        views.TestEditView.as_view(),
        name="edit_project"),
    url(
        r"applications/$", views.AllApplications.as_view(), name="applications"
    ),
    url(
        r"applications/(?P<pk>\d+)$", views.ApplicationsDetailView.as_view(),
        name="application_detail"
    ),
    url(
        r"applications/(?P<pk>\d+)/(?P<decision>\w+)$",
        views.AcceptRejectApplicationView.as_view(),
        name="application_decision"),
    url(r'delete/(?P<pk>\d+)$', views.DeleteProjectView.as_view(),
        name='delete'),
]

templates/index.html
{% extends 'layout.html' %}
{% block body_content %}
    <div class="bounds circle--page">
        <div class="circle--page--header circle--fluid">
            <div class="circle--fluid--cell circle--fluid--primary">
                <h2>Projects</h2>
            </div>
            <div class="circle--fluid--cell circle--fluid--secondary">
                {% if user.is_authenticated %}
                    <a class="button button-primary icon-on-left"
                       href="{% url 'projects:create_project' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 13 13" style="enable-background:new 0 0 13 13;" xml:space="preserve" class="add">
            <polygon points="7,6 7,0 6,0 6,6 0,6 0,7 6,7 6,13 7,13 7,7 13,7 13,6 "/>
          </svg>
                        New Project
                    </a>
                {% else %}
                    <h1> Please create a account to use all the features</h1>
                {% endif %}
            </div>
        </div>

        <div class="grid-25">
            <div class="circle--filter circle--secondary--module">
                <h4>Project Needs</h4>
                <ul class="circle--filter--list">
                    {% url 'projects:all_projects' as test %}
                    <li><a  {% if request.get_full_path == test %}
                        class="selected"
                    {% endif %} >All Needs</a></li>
                    <li><a href="?filter=android"
                            {% if 'android' in request.get_full_path %}
                           class="selected"
                            {% endif %}>Android Developer</a></li>
                    <li><a href="?filter=designer"
                            {% if 'designer' in request.get_full_path %}
                           class="selected"
                            {% endif %}>Designer</a></li>
                    <li><a href="?filter=java"
                            {% if 'java' in request.get_full_path %}
                           class="selected"
                            {% endif %}>Java Developer</a></li>
                    <li><a href="?filter=php"
                            {% if 'php' in request.get_full_path %}
                           class="selected"
                            {% endif %}>PHP Developer</a></li>
                    <li><a href="?filter=python"
                            {% if 'python' in request.get_full_path %}
                           class="selected"
                            {% endif %}>Python Developer</a></li>
                    <li><a href="?filter=Rails"
                            {% if 'Rails' in request.get_full_path %}
                           class="selected"
                            {% endif %}>Rails Developer</a></li>
                    <li><a href="?filter=wordpress"
                            {% if 'wordpress' in request.get_full_path %}
                           class="selected"
                            {% endif %}>WordPress Developer</a></li>
                    <li><a href="?filter=ios"
                            {% if 'ios' in request.get_full_path %}
                           class="selected"
                            {% endif %}>iOS Developer</a></li>
                </ul>
            </div>
        </div>

        <div class="grid-70 grid-push-5">
            <table class="u-full-width circle--table">
                <thead>
                <tr>
                    <th>Project Title</th>
                    <th class="circle--cell--right">Project Needs</th>
                </tr>
                </thead>
                <tbody>
                {% for project in project_list %}
                    {% if not project.completed %}
                        <tr class="clickable-row"
                            data-href="{% url 'projects:detail' pk=project.pk %}">
                            <td>
                                <h3>{{ project.title }}</h3>
                            </td>
                            <td class="circle--cell--right">
                                {% for position in project.positions.all %}
                                    <span class="secondary-label">{{ position.title }}</span>
                                    </br>
                                {% endfor %}
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

templates/layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>

    <!-- Basic Page Needs
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta charset="utf-8">
    <title>Circle</title>
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Mobile Specific Metas
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- FONTS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500'
          rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine'
          rel='stylesheet' type='text/css'>

    <!-- CSS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <link rel="stylesheet" href="{% static 'css/global.css' %}">

    <!-- JS
    –––––––––––––––––––––––––––––––––––––––––––––––––– -->
    <script type="text/javascript"
            src="https://code.jquery.com/jquery-2.2.0.min.js"></script>
    <script type="text/javascript"
            src="{% static 'js/autogrow.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/global.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/jquery.formset.js' %}"></script>

</head>
<body>
<header class="circle--header">
    <form action="{% url 'projects:all_projects' %}">
        <div class="bounds">
            <div class="circle--fluid">
                <div class="circle--fluid--cell">
                    <h1 class="hide-text circle--logo"><a class="logo"
                                                          href="{% url 'home' %}">Circle</a>
                    </h1>
                </div>
                <div class="circle--fluid--cell circle--fluid--primary">
                    <div class="circle--search">

                        <input type="text" placeholder="Search Projects..."
                               name="q"/>
                        <button type="submit">
                            <svg version="1.1" class="search" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 12 12" xml:space="preserve">
                <path d="M12,10.6L8.3,6.9C8.7,6.2,9,5.4,9,4.5C9,2,7,0,4.5,0S0,2,0,4.5S2,9,4.5,9c0.9,0,1.7-0.3,2.4-0.7l3.7,3.7L12,10.6z M2,4.5
                C2,3.1,3.1,2,4.5,2S7,3.1,7,4.5C7,5.9,5.9,7,4.5,7S2,5.9,2,4.5z"/>
              </svg>
                        </button>

                    </div>
                </div>
                <div class="circle--fluid--cell circle--fluid--secondary">
                    <nav>
                        <ul class="circle--inline">
                            {% if not user.is_authenticated %}
                                <li><a href="{% url 'accounts:sign_up' %}">Sign
                                    Up</a></li>
                                <li><a href="{% url 'accounts:sign_in' %}">Sign
                                    In</a></li>
                            {% else %}
                                <li><a href="{% url 'accounts:logout' %}">Log
                                    out</a></li>
                                <li>
                                    <a href="{% url 'accounts:profile' pk=user.pk %}">View
                                        profile</a></li>
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </form>
</header>
{% if messages %}
    <div>

        {% for message in messages %}
            <h3 align="center">{{ message }}</h3>
        {% endfor %}


    </div>
{% endif %}
{% block body_content %}

{% endblock %}
</body>
</html>

templates/search.html
{% extends 'layout.html' %}
{% block body_content %}
    <h1 align="center">Please login or sign up to use the site</h1>
{% endblock %}